packages:
  - packages/*

enableScripts: true

onlyBuiltDependencies:
  - better-sqlite3

ignoredBuiltDependencies:
  - esbuild
  - node-pty
  - onnxruntime-node
  - protobufjs
  - sharp

overrides:
  onnxruntime-web: ./empty

unsafePerm: true
